### ISSUE TITLE
Rename installed package from `chipwhispererminimal` to `chipwhisperer`

### ISSUE THREAD

**Issue by vogelpi** [newaetech/chipwhisperer-minimal#2]
Hi @alex-dewar ,
we are currently facing an issue with chipwhisperer-minimal.

We cannot import `chipwhisperer`:
```
>>> import chipwhisperer as cw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'chipwhisperer'
```

If we import `chipwhispererminimal` instead, accessing the CW310 fails pretty quickly as chipwhisperer-minimal seems to have internal references to chipwhisperer which we install no longer:
```
import chipwhispererminimal as cw
>>> target = cw.target(None, cw.targets.CW310)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pirmin/.local/lib/python3.8/site-packages/chipwhispererminimal/__init__.py", line 6, in target
    rtn = target_type()
  File "/home/pirmin/.local/lib/python3.8/site-packages/chipwhispererminimal/capture/targets/CW310.py", line 67, in __init__
    import chipwhisperer as cw
ModuleNotFoundError: No module named 'chipwhisperer'
```

I think the name of the installed Python package should be changed from `chipwhispererminimal` to `chipwhisperer`. Could you take a look please?

**Comment by alex-dewar** [comment]
Hi,

Thanks for the report on this. It should be fixed. Let me know if it works for you

**Comment by drewmacrae** [comment]
This appears to work now. Thank you!

**Comment by alex-dewar** [comment]
Happy to help 👍
